version: '3.7'

services:
  flask-app:
    container_name: flask-app
    build: .
    ports:
      - "5001:5001"
    deploy:
      resources:
        limits:
          memory: 512m
    env_file:
      - .env 
    restart: never
    command: gunicorn -w 2 -k gevent -b 0.0.0.0:5001 app:app
